from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import Any

from . import trade_plan_calibration_v3 as v3


AUTO_PLAN_SOURCE = "AUTO_ALPACA_1M_CHART"


def _adapt_auto_text(value: Any) -> str:
    text = str(value or "")
    replacements = (
        ("user-supplied chart screenshot", "automatically generated Alpaca 1-minute chart"),
        ("user supplied chart screenshot", "automatically generated Alpaca 1-minute chart"),
        ("newer chart screenshot", "newer automatically generated Alpaca 1-minute chart context"),
        ("new chart screenshot", "new automatically generated Alpaca 1-minute chart context"),
        ("screenshot", "automatic chart"),
    )
    for source, target in replacements:
        text = text.replace(source, target).replace(source.title(), target)
    return text


def _adapt_auto_result(parsed: dict[str, Any]) -> dict[str, Any]:
    result = dict(parsed)
    for field in ("summary", "setup_type", "entry_trigger", "invalidation"):
        result[field] = _adapt_auto_text(result.get(field))
    for field in ("positive_factors", "risk_factors", "chart_observations", "what_to_confirm"):
        result[field] = list(
            dict.fromkeys(
                _adapt_auto_text(value)
                for value in (result.get(field) or [])
                if str(value or "").strip()
            )
        )
    return result


def analyze_automatic_trade_plan(
    snapshot: dict[str, Any],
    *,
    image_path: str | Path,
    bars: list[dict[str, Any]],
    api_key: str,
    model: str,
) -> v3.base.TradePlanResult:
    """Run Trade Plan v3 using a chart generated by TrendVisionAI itself."""
    from openai import OpenAI

    request_snapshot = v3._normalize_unobserved_zero_borrow(snapshot)
    market = request_snapshot.get("alpaca_market_context") or {}
    if not market.get("current_context_usable"):
        raise v3.StaleMarketDataError(v3._freshness_error(market))

    image_url, image_sha = v3.base._image_data_url(image_path)
    request_snapshot = copy.deepcopy(request_snapshot)
    request_snapshot["trade_plan_version"] = v3.TRADE_PLAN_VERSION
    request_snapshot["plan_source"] = AUTO_PLAN_SOURCE
    request_snapshot["automatic_chart_context"] = {
        "source": "Alpaca recent 1-minute bars",
        "feed": market.get("feed"),
        "bar_count": len(bars),
        "bars": bars,
        "interpretation": (
            "The image is rendered by TrendVisionAI from these bars. It is not a third-party chart, "
            "contains no trade recommendation overlay, and inherits the feed limitations of the supplied Alpaca data."
        ),
    }
    request_snapshot["chart_screenshot"] = {
        "sha256": image_sha,
        "role": (
            "TrendVisionAI-generated chart from Alpaca 1-minute bars. "
            "No third-party BUY/SELL/SL/TP recommendation overlay is present."
        ),
    }

    auto_instructions = (
        "AUTOMATIC CHART MODE:\n"
        "- The image was generated by TrendVisionAI from the structured automatic_chart_context bars.\n"
        "- It is not a user screenshot and it contains no third-party trade recommendation levels.\n"
        "- Use the image and bar list only for chart structure; exact current planning price/quote still comes from alpaca_market_context.\n"
        "- If feed=IEX, both the rendered bars and live quote/trade observations are partial-venue evidence.\n\n"
        + v3._INSTRUCTIONS_V3
    )

    client = OpenAI(api_key=api_key)
    response = client.responses.create(
        model=model,
        instructions=auto_instructions,
        input=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": json.dumps(request_snapshot, ensure_ascii=False, separators=(",", ":")),
                    },
                    {"type": "input_image", "image_url": image_url, "detail": "high"},
                ],
            }
        ],
        text={"format": v3._SCHEMA_V3},
    )
    parsed = v3.calibrate_trade_plan_payload_v3(
        json.loads(response.output_text),
        request_snapshot,
    )
    parsed = _adapt_auto_result(parsed)

    entry_high = v3.base._num(parsed.get("entry_high"))
    stop = v3.base._num(parsed.get("stop_loss"))
    target_1 = v3.base._num(parsed.get("target_1"))
    target_2 = v3.base._num(parsed.get("target_2"))

    return v3.base.TradePlanResult(
        ticker=str(request_snapshot.get("ticker") or "?").upper(),
        model=model,
        decision=str(parsed["decision"]),
        confidence=str(parsed["confidence"]),
        risk_level=str(parsed["risk_level"]),
        chart_structure=str(parsed["chart_structure"]),
        setup_type=str(parsed.get("setup_type") or ""),
        summary=str(parsed.get("summary") or ""),
        entry_low=v3.base._num(parsed.get("entry_low")),
        entry_high=entry_high,
        stop_loss=stop,
        target_1=target_1,
        target_2=target_2,
        risk_reward_target_1=v3.base._risk_reward(entry_high, stop, target_1),
        risk_reward_target_2=v3.base._risk_reward(entry_high, stop, target_2),
        entry_trigger=str(parsed.get("entry_trigger") or ""),
        invalidation=str(parsed.get("invalidation") or ""),
        positive_factors=[str(value) for value in parsed.get("positive_factors") or []],
        risk_factors=[str(value) for value in parsed.get("risk_factors") or []],
        chart_observations=[str(value) for value in parsed.get("chart_observations") or []],
        what_to_confirm=[str(value) for value in parsed.get("what_to_confirm") or []],
        created_at=v3.base._now_iso(),
        plan_version=v3.TRADE_PLAN_VERSION,
    )
